### ISSUE TITLE
Question on the always visible part in the menu item: Custom font or two rows possible?

### ISSUE THREAD

**Issue by porg** [mzdr/timestamp#31]
In the dropdown menu I guess you have full HTML/CSS flexibility as it seems in 
        timestamp/app/components/calendar/calendar-today.html

My question: Can you also use full HTML/CSS layout (and as such custom smaller font size or a two row layout to condense information) in the part which is always visible (the menu item itself) ?

Or do you need to use macOS layouting capabilities there? Could the forementioned layout be achieved with it? Or does macOS put tougher restrictions on you there like one font size throughout the entire menu bar?

**Comment by mzdr** [comment]
Hey there,

if you are talking about the right-click system tray dropdown menu I have to say this is native and not styled at all by Timestamp. Furthermore the new release (v1.1.0) removes this right-click menu. But to be honest, I am not sure what you are talking about exactly. 

Can you maybe elaborate with screenshots? Feel free to reopen if there is an issue.

**Comment by porg** [comment]
Screenshot to elaborate on my original question:

![Timestamp - Menubar item and Popup](https://user-images.githubusercontent.com/737143/117654231-c0ee0580-b195-11eb-9943-e5eb1cafaa43.png)

**Comment by mzdr** [comment]
Ah, now I get it. The system menu itself only supports strings, so you have almost zero control in terms of layouting. But you can also create a canvas and render it inside the system menu, which would give your endless flexibility but also would require quite an effort.

**Comment by porg** [comment]
Understood. When I requested this in 2/2019 I really intended to use Timestamp.app and was interested in a narrower menu-item of it.

But since then macOS Big Sur introduced two things which made Timestamp obsolete for me:
- The native date/time menu item now also functions as a notif on/off toggle, hence its space consumption is justified
- You now can get a mini calendar simply by adding the widget "Calendar M" on top of your widgets to show/reveal with one click only. Ofc it has less functionality than Timestamp (no prev/next month), but most often I just needed if as a quick weekdate/date time lookup (as Windows has had it for decades)

Consider this issue also closes from my side.

Thanks for providing a response in the issue tracker and this software in general!

**Comment by mzdr** [comment]
Hey man, thanks for your response. 

I totally understand your points. I have also noticed the changes introduced by Big Sur. Now it is not possible anymore to remove the date/time display because it’s connected to the notification area as you have mentioned. My initial thought for developing Timestamp was to find something similar to Day-O because it stopped running on newer macOS versions. After some time I had the idea to enrich it with a calendar. This is when I released Timestamp for the first time.

Years later, which means today, I started working on it again. Mostly because I had the idea to visually overhaul the calendar and make it more beautiful. I had several attempts a couple of months/years ago but now I’m close to releasing the update. :) 

Anyway, I am glad Timestamp was of use for you. Thanks for taking the time to engage and trying to improve it. Maybe we will hear us again once the new update is released.
